kind: pipeline
type: docker
name: mblog-backend
trigger:
  branch:
    - prod
    - prod-allinone
  event:
    - push

steps:
  - name: maven build
    image: maven:3.9.1-sapmachine-17
    volumes:
      - name: maven-repo
        path: /root/.m2
    commands:
      - mvn -DskipTests=true clean package

  - name: docker build prod
    image: plugins/docker
    when:
      branch:
        - prod
    settings:
      mirror: https://mm0rc4mq.mirror.aliyuncs.com
      registry: 192.168.2.33:47382
      insecure: true
      repo: 192.168.2.33:47382/kingwrcy/mblog-backend
      tags: latest
      cache_from: 192.168.2.33:47382/kingwrcy/mblog-backend:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: docker build prod-allinone
    image: plugins/docker
    when:
      branch:
        - prod-allinone
    settings:
      dockerfile: Dockerfile-allinone
      mirror: https://mm0rc4mq.mirror.aliyuncs.com
      registry: 192.168.2.33:47382
      insecure: true
      repo: 192.168.2.33:47382/kingwrcy/mblog
      tags: latest
      cache_from: 192.168.2.33:47382/kingwrcy/mblog:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: start service
    image: appleboy/drone-ssh
    when:
      branch:
        - prod
    settings:
      host:
        - 192.168.2.33
      username: root
      key:
        from_secret: ds920_private_key
      port: 22
      command_timeout: 2m
      script:
        - cd /volume1/docker/drone/mblog-backend/
        - chmod +x ./startup.sh
        - ./startup.sh

volumes:
  - name: maven-repo
    host:
      path: /var/lib/maven-repo